import { z } from 'zod';

export const CreateJobSchema = z.object({
  // code will be generated by server; optional for backwards compatibility
  code: z.string().min(1).optional(),
  workType: z.string().min(1),
  description: z.string().min(1),
  priority: z.enum(['Baja', 'Media', 'Alta']),
  clientName: z.string().min(1),
  clientPhone: z.string().min(1),
  clientEmail: z.string().email().optional().nullable(),
  clientAddress: z.string().min(1),
  clientCompany: z.string().optional().nullable(),
  clientAppEmail: z.string().email().optional().nullable(),
  clientAppPhone: z.string().optional().nullable(),
  sendAppInstructions: z.boolean().optional().default(false),
  estimatedDelivery: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  assignedWorker: z.string().min(1),
  paymentAmount: z.string().refine(v => !isNaN(Number(v)) && Number(v) >= 0, { message: 'Invalid paymentAmount' }),
  paymentStatus: z.enum(['Pendiente', 'Pagado']),
  materials: z.string().optional().nullable(),
  specifications: z.string().optional().nullable(),
  dateCreated: z.string().regex(/^\d{4}-\d{2}-\d{2}$/)
}).superRefine((data, ctx) => {
  // estimatedDelivery >= dateCreated
  const ed = new Date(data.estimatedDelivery);
  const dc = new Date(data.dateCreated);
  if (ed < dc) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'estimatedDelivery must be >= dateCreated' });
});

export type CreateJobBody = z.infer<typeof CreateJobSchema>;
